export const COURSE_PRODUCTS = {
  'ai-first-student': {
    id: 'ai-first-student',
    title: '2-Hour Student Systems Coaching',
    amountCents: 15900,
    currency: 'USD',
    portalUrl: 'https://portal.autonateai.com/#/tracks/student',
    grantsPortalAccess: true,
    fulfillmentType: 'portal-access',
  },
  'agentic-ai-workshop-apr-18-2026': {
    id: 'agentic-ai-workshop-apr-18-2026',
    title: 'Agentic AI Live Workshop',
    amountCents: 15900,
    currency: 'USD',
    portalUrl: 'https://portal.autonateai.com/#/tracks/student',
    grantsPortalAccess: true,
    fulfillmentType: 'portal-access',
    maxSuccessfulPayments: 50,
    eventDateLabel: 'Saturday, April 18, 2026',
    eventTimeLabel: '10:00 AM - 12:30 PM',
  },
  'ai-first-researcher': {
    id: 'ai-first-researcher',
    title: 'AI-First Researcher',
    amountCents: 18900,
    currency: 'USD',
    portalUrl: 'https://portal.autonateai.com/#/tracks/researcher',
    grantsPortalAccess: true,
    fulfillmentType: 'portal-access',
  },
  'student-systems-program-25-2h': {
    id: 'student-systems-program-25-2h',
    title: 'Student Systems Workshop Program',
    amountCents: 322500,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 25,
    workshopHours: 2,
  },
  'student-systems-program-25-3h': {
    id: 'student-systems-program-25-3h',
    title: 'Student Systems Workshop Program',
    amountCents: 385000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 25,
    workshopHours: 3,
  },
  'student-systems-program-25-4h': {
    id: 'student-systems-program-25-4h',
    title: 'Student Systems Workshop Program',
    amountCents: 447500,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 25,
    workshopHours: 4,
  },
  'student-systems-program-50-2h': {
    id: 'student-systems-program-50-2h',
    title: 'Student Systems Workshop Program',
    amountCents: 595000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 50,
    workshopHours: 2,
  },
  'student-systems-program-50-3h': {
    id: 'student-systems-program-50-3h',
    title: 'Student Systems Workshop Program',
    amountCents: 720000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 50,
    workshopHours: 3,
  },
  'student-systems-program-50-4h': {
    id: 'student-systems-program-50-4h',
    title: 'Student Systems Workshop Program',
    amountCents: 845000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 50,
    workshopHours: 4,
  },
  'student-systems-program-100-2h': {
    id: 'student-systems-program-100-2h',
    title: 'Student Systems Workshop Program',
    amountCents: 1090000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 100,
    workshopHours: 2,
  },
  'student-systems-program-100-3h': {
    id: 'student-systems-program-100-3h',
    title: 'Student Systems Workshop Program',
    amountCents: 1340000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 100,
    workshopHours: 3,
  },
  'student-systems-program-100-4h': {
    id: 'student-systems-program-100-4h',
    title: 'Student Systems Workshop Program',
    amountCents: 1590000,
    currency: 'USD',
    grantsPortalAccess: false,
    fulfillmentType: 'organization-program',
    studentCount: 100,
    workshopHours: 4,
  },
};

export function getCourseProduct(productId) {
  return COURSE_PRODUCTS[productId] ?? null;
}
